### ISSUE TITLE
devServer와 실제 배포 사이의 여백 차이 확인

### ISSUE THREAD

**Issue by junhobaik** [junhobaik/junhobaik.github.io#18]
로컬 개발 환경과 배포된 것 사이에 여백이 차이가 있는 것을 확인함,
예, postLink 컴포넌트 안의 엘리먼트들
문제점 파악하기.

**Comment by junhobaik** [comment]
normalize.css 의 영향으로 보임,
normalize의 글로벌 적으로 적용되는 `line-height: 1.15`가 devServer에서만 작동하고 테스트 환경인 크롬, 파이어폭스에서는 적용되지 않아 차이점이 발생함

```css
html {
  line-height: 1.666 !important;
}
```

위 코드로 해결
